name: auth_flutter_sdk
description: Casdoor_flutter_sdk will allow you to easily connect your application to the Casdoor authentication system without having to implement it from scratch.
version: 1.6.0
homepage: https://github.com/casdoor/casdoor-flutter-sdk

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  path: ^1.8.2
  path_provider: ^2.1.1
  desktop_webview_window:
    path: ../desktop_webview_window
  flutter_inappwebview: ^6.0.0
  http: ^1.0.0
  crypto: ^3.0.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: auth_flutter_sdk
    platforms:
      android:
        dartPluginClass: CasdoorFlutterSdkMobile
      ios:
        dartPluginClass: CasdoorFlutterSdkMobile
      linux:
        dartPluginClass: CasdoorFlutterSdkDesktop
      macos:
        dartPluginClass: CasdoorFlutterSdkDesktop
      windows:
        dartPluginClass: CasdoorFlutterSdkDesktop
      web:
        pluginClass: CasdoorFlutterSdkWeb
        fileName: src/casdoor_flutter_sdk_web.dart

false_secrets:
  - /credentials.json
